backend/models/VtComment.php
<?php

namespace backend\models;
use common\models\VtCommentBase;

use Yii;

class VtComment extends \common\models\VtCommentBase
{
    public $date;
    public $numOfRecord;
    public $totalComment;
    public $waitingComment;
    public $approvedComment;
    public $declinedComment;
    public $below5MinApproval;


    public function checkApprovePermission()
    {
        if (Yii::$app->user->can('vt-comment')) {
            return true;
        } else {
            return false;
        }
    }

    public function getCreatedByName()
    {
        $objUsername = VtUser::getById($this->user_id);
        return ($objUsername) ? (($objUsername->full_name)?$objUsername->full_name:$objUsername->msisdn) : $this->user_id;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'content_id' => Yii::t('app', 'ID Nội dung'),
            'type' => Yii::t('app', 'Loại'),
            'user_id' => Yii::t('app', 'ID Khách hàng'),
            'content' => Yii::t('app', 'Nội dung'),
            'parent_id' => Yii::t('app', 'Bình luận cha'),
            'status' => Yii::t('app', 'Trạng thái'),
            'bad_word_filter' => Yii::t('app', 'Bad Word Filter'),
            'approve_by' => Yii::t('app', 'Phê duyệt bởi'),
            'reason' => Yii::t('app', 'Lý do'),
            'like_count' => Yii::t('app', 'Like Count'),
            'created_at' => Yii::t('app', 'Tạo lúc'),
            'updated_at' => Yii::t('app', 'Cập nhật lúc'),
            'comment' => Yii::t('app', 'Bình luận'),
            'comment_count' => Yii::t('app', 'Số lượng bình luận'),
        ];
    }

    /** list total of record depending on each reason type
     * @param $fromTime, $toTime, $reasonId
     * @return $reasonSummary
     * @author thuynd10
     */
    public static function summaryReason($fromTime, $toTime, $reasonId){
        $reasonSummary = self::find()
            ->select(['count(id) as numOfRecord', 'reason'])
            ->where(['and',
                ['>=', 'created_at', $fromTime],
                ['<=', 'created_at', $toTime],
                ['status' => 2]
            ]);
        if($reasonId != null){
            $reasonSummary->andWhere(['reason' => $reasonId]);
        }
        $reasonSummary = $reasonSummary->groupBy(['reason'])->all();
        return $reasonSummary;
    }

    /** count 'total of Comments', 'number of waiting comments', 'number of approved comments', 'number of declined comments'
     *  'number of comments which are reviewed at a duration of time below 5 minutes'
     * @param $fromTime, $toTime, $reasonId
     * @return $query
     * @author thuynd10
     */
    public static function getCommentData($fromTime, $toTime, $reasonId){
        $date_subquery = self::find()->select(['distinct(date(created_at)) as date'])
            ->where(['and', ['>=', 'created_at', $fromTime], ['<=', 'created_at', $toTime]]);
            if($reasonId != ''){
                $date_subquery = $date_subquery->andWhere(['reason' => $reasonId]);
            }
            $date_subquery = $date_subquery->orderBy(['date' => SORT_DESC]);
        $total_comment_subquery = self::find()->select('date(created_at) as date, count(id) as totalComment')
            ->where(['and', ['>=', 'created_at', $fromTime], ['<=', 'created_at', $toTime]])
            ->groupBy(['date'])->orderBy(['date' => SORT_DESC]);
        $waiting_comment_subquery = self::find()->select('date(created_at) as date, count(id) as waitingComment')
            ->where(['and', ['>=', 'created_at', $fromTime], ['<=', 'created_at', $toTime], ['status' => 0]])
            ->groupBy(['date'])->orderBy(['date' => SORT_DESC]);
        $approved_comment_subquery = self::find()->select('date(created_at) as date, count(id) as approvedComment')
            ->where(['and', ['>=', 'created_at', $fromTime], ['<=', 'created_at', $toTime], ['status' => 1]])
            ->groupBy(['date'])->orderBy(['date' => SORT_DESC]);
        $declined_comment_subquery = self::find()->select('date(created_at) as date, count(id) as declinedComment')
            ->where(['and', ['>=', 'created_at', $fromTime], ['<=', 'created_at', $toTime], ['status' => 2]]);
            if($reasonId != ''){
                $declined_comment_subquery = $declined_comment_subquery->andWhere(['reason' => $reasonId]);
            }
            $declined_comment_subquery = $declined_comment_subquery->groupBy(['date'])->orderBy(['date' => SORT_DESC]);
        $below5MinApproval_subquery = self::find()->select('date(created_at) as date, count(id) as below5MinApproval')
            ->where(['and',
                ['>=', 'created_at', $fromTime],
                ['<=', 'created_at', $toTime],
                ['!=', 'status', 0],
                ['<', 'timediff(updated_at, created_at)', '00:05:00']
            ])
            ->groupBy(['date'])->orderBy(['date' => SORT_DESC]);
        $query = self::find()
            ->select('a.date, b.totalComment, c.waitingComment, d.approvedComment, e.declinedComment, f.below5MinApproval')
            ->from(['a' => $date_subquery])
            ->leftJoin(['b' => $total_comment_subquery], 'a.date = b.date')
            ->leftJoin(['c' => $waiting_comment_subquery], 'a.date = c.date')
            ->leftJoin(['d' => $approved_comment_subquery], 'a.date = d.date')
            ->leftJoin(['e' => $declined_comment_subquery], 'a.date = e.date')
            ->leftJoin(['f' => $below5MinApproval_subquery], 'a.date = f.date')
        ;
        return $query;
    }


    public  function getVideoNameByContentID($contentID){
        $query = VtCommentBase::getById($this->content_id);
        return ($query) ? $query-> name : $this -> content_id;
    }
}

backend/controllers/VtCommentController.php
<?php

namespace backend\controllers;

use backend\models\VtActionLog;
use common\models\MongoDBModel;
use common\models\VtUserBase;
use common\models\VtVideoBase;
use Yii;
use backend\models\VtComment;
use backend\models\VtCommentSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * VtCommentController implements the CRUD actions for VtComment model.
 */
class VtCommentController extends Controller
{
    public  function init()
    {
        //parent::init(); // TODO: Change the autogenerated stub
        //$this->language = Yii::$app->session->get('lang', 'lo');
        $langss = Yii::$app->session->get('lang', 'lo');
        //var_dump($langss);die;
        // kiem tra xem this->language co nam trong mang khong
        $languagePool=Yii::$app->params['languagepool'];
        //var_dump($languagePool);die;
        // neu trong mang
        if(in_array($langss,$languagePool)){
            Yii::$app->language=$langss;
        }else{
            Yii::$app->language=Yii::$app->params['mainLanguage'];
        }
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all VtComment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VtCommentSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Updates an existing VtComment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionApprove()
    {
        if (!Yii::$app->getRequest()->validateCsrfToken()) {
            return "CSRF TOKEN INVALID";
        }
        $id = Yii::$app->request->post('id',0);
        $action = Yii::$app->request->post('action',0);
        //Thuynd10_added_20180809.
        $reason = Yii::$app->request->post('reason','');
        $model = $this->findModel($id);
        if ($model) {
            switch ($action) {
                case 'approve':
                    $model->status = 1;
                    $model->updated_at = date("Y-m-d H:i:s");
                    $model->approve_by = Yii::$app->user->id;
                    $model->reason = trim($reason);
//                    var_dump($model->save(true));die;
                    $model->save(false);
                    //- Add event Mongodb
                    $userCreate = VtUserBase::getById($model->user_id);

                    $objVideo = VtVideoBase::findOne(["id" => $model->content_id]);

//                    MongoDBModel::insertEvent(MongoDBModel::COMMENT, $model->content_id, $model->user_id, ($userCreate) ? $userCreate->msisdn : "", $model->id, $objVideo->created_by);

                    VtActionLog::insertLog(VtActionLog::MODULE_COMMENT, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);
                    return json_encode(['errorCode' => 200, "message" => Yii::t('backend', 'Duyệt thành công')]);
                    break;

                case 'delete':
                    $model->status = 2;
                    $model->updated_at = date("Y-m-d H:i:s");
                    $model->approve_by = Yii::$app->user->id;
                    $model->reason = trim($reason);
//                    if ($model->reason != null)
//                    {
//                        $model->save(false);
//                    }
                    $model->save(false);
                    VtActionLog::insertLog(VtActionLog::MODULE_COMMENT, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);
                    return json_encode(['errorCode' => 200, "message" => Yii::t('backend','Hạ duyệt thành công')]);
                    break;
            }
        } else {
            return json_encode(['errorCode' => 201, "message" => Yii::t('backend','Không tìm thấy bình luận')]);
        }


    }

    /**
     * Deletes an existing VtComment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        VtActionLog::insertLog(VtActionLog::MODULE_COMMENT, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);
        $model->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the VtComment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return VtComment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = VtComment::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $homeUrl = Yii::$app->request->get('home-url', '');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success',Yii::t('backend','Cập nhật thành công'));

            VtActionLog::insertLog(VtActionLog::MODULE_COMMENT, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);

            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'homeUrl' => $homeUrl
            ]);
        }
    }
}

backend/views/vt-comment/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\VtComment */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vt-comment-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'type')->textInput(['readonly' => 'readonly']) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6, 'readonly' => 'readonly']) ?>

    <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vt-comment/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\VtCommentSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vt-comment-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'content_id') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'content') ?>

    <?php // echo $form->field($model, 'parent_id') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'bad_word_filter') ?>

    <?php // echo $form->field($model, 'approve_by') ?>

    <?php // echo $form->field($model, 'reason') ?>

    <?php // echo $form->field($model, 'like_count') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <?php // echo $form->field($model, 'comment_count') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('backend', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vt-comment/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\VtComment */

$this->title = Yii::t('backend', 'Create Vt Comment');
$this->params['breadcrumbs'][] = ['label' => 'Vt Comments', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vt-comment-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/vt-comment/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\web\JsExpression;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use backend\assets\CommentAsset;
CommentAsset::register($this);

/* @var $this yii\web\View */
/* @var $searchModel backend\models\VtCommentSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Vt Comments');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vt-comment-index" style="word-break: break-word">
    <input type="hidden" id="approve-comment-action" value="/vt-comment/approve">
    <!--h1><?= Html::encode($this->title) ?></h1-->
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?php
    $statusValue = $searchModel->status;
    $comment_status_dropdown_value = Yii::$app->params['comment.status.dropdown.value'];
    for ($i = 0; $i < count($comment_status_dropdown_value); $i++) {
        $comment_status_dropdown_value[$i] = Yii::t('backend', $comment_status_dropdown_value[$i]);
    }

    $setting_comment_decline = Yii::$app->params['setting.comment.decline'];
    for ($i = 1; $i < count($setting_comment_decline) + 1; $i++) {
        $setting_comment_decline[$i] = Yii::t('wap', $setting_comment_decline[$i]);
    }
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
//            'id',
            [
                'attribute' => 'comment',
                'label' => \Yii::t('app', 'Bình luận'),
                'format' => 'raw',
                'value' => function ($model, $key, $index, $widget) {
                    return '<a href="' . \yii\helpers\Url::toRoute(['vt-comment/update', 'id' => $model->id, 'home-url' => base64_encode(Yii::$app->request->url)]) .'">'. Html::encode($model->comment) .'</a>';
                }
            ],
            'type',
            [
                'attribute' => 'created_at',
                'label' => Yii::t('backend','Tạo lúc'),
                'format' => 'raw',
                'value' => function ($model) {
                    return $model->created_at;
                },
                'filter' => \kartik\daterange\DateRangePicker::widget([
                    'model'=>$searchModel,
                    'name'=>'range_created_at',
                    'attribute' => 'created_at',
                    'value'=> date('Y-m-00 H:i:s').' - '. date('Y-m-d H:i:s'),
                    'convertFormat'=>true,
//                    'readonly' => true,
                    'pluginOptions'=>[
                        'opens' => 'left',
                        'alwaysShowCalendars' => true,
                        'timePicker'=>true,
                        'timePicker24Hour' => true,
                        'locale'=>['format'=>'Y-m-d H:i:s']
                    ],
                    'options' => [
                        'class'=>'form-control',
                        'placeholder' => "---" . Yii::t('backend', 'Thời gian tạo') . "---"
                    ],
                ])
            ],
            [
                'attribute' => 'updated_at',
                'label' => Yii::t('backend','Phê duyệt lúc'),
                'format' => 'raw',
                'value' => function ($model) {
                    return $model->updated_at;
                },
                'filter' => \kartik\daterange\DateRangePicker::widget([
                    'model'=>$searchModel,
                    'name'=>'range_updated_at',
                    'attribute' => 'updated_at',
                    'value'=> date('Y-m-00 H:i:s').' - '. date('Y-m-d H:i:s'),
                    'convertFormat'=>true,
                    'pluginOptions'=>[
                        'timePicker'=>true,
                        'timePicker24Hour' => true,
                        'locale'=>['format'=>'Y-m-d H:i:s']
                    ],
                    'options' => [
                        'class'=>'form-control',
                        'placeholder' => '---'.Yii::t('backend','Thời gian phê duyệt').'---'
                    ]
                ])
            ],
            'content',
            [
                'attribute' => 'status',
                'label' => \Yii::t('app', 'Trạng thái'),
                'format' => 'raw',
                'value' => function ($model, $key, $index, $widget) {
                    if ($model->status == \backend\models\VtComment::WAIT_APPROVE) return Yii::t('backend', 'Chờ duyệt');
                    if ($model->status == \backend\models\VtComment::ACTIVE) return Yii::t('backend', 'Đã duyệt');
                    if ($model->status == \backend\models\VtComment::DISAPPROVE) return Yii::t('backend', 'Không duyệt');
                },
                'filter' => Html::activeDropDownList($searchModel, 'status', $comment_status_dropdown_value,['class'=>'commentStatus form-control','prompt' => '']),
            ],
            [
                'attribute' => 'reason',
                'label' => \Yii::t('app', 'Lý do'),
                'value' => function ($model) {
                    $allReason = Yii::$app->params['setting.comment.decline'];
                    for ($i = 1; $i < count($allReason) + 1; $i++) {
                        $allReason[$i] = Yii::t('wap', $allReason[$i]);
                    }
                    $reason = $model->reason;
                    if($reason != ''){
                        return $allReason[$reason];
                    } else {
                        return "";
                    }
                },
                'filter' => Html::activeDropDownList($searchModel, 'reason', $setting_comment_decline,['class'=>'form-control','prompt' => '']),
                'visible' => $statusValue == 2 ? true : false,
            ],
            [
                'attribute' => 'user_id',
                'label' => Yii::t('backend','Tài khoản'),
                'format' => 'raw',
                'value' => function ($model) {
                    if (isset($model->user)) {
                        return
                            '<strong>' . ((isset($model->user) && !empty($model->user->full_name)) ? htmlentities($model->user->full_name) : $model->user->msisdn) . '</strong>';
                    } else {
                        return '';
                    }

                },
                'filter' => \kartik\select2\Select2::widget([
                    'model' => $searchModel,
                    'attribute' => 'user_id',
                    'initValueText' => $searchModel->getCreatedByName(),
                    'options' => ['placeholder' => "---" . Yii::t('backend','Người tạo') . "---"],
                    'pluginOptions' => [
                        'allowClear' => true,
                        'minimumInputLength' => 3,
                        'language' => [
                            'errorLoading' => new JsExpression("function () { return '" . Yii::t('backend', 'Loading ...') . "'; }"),
                        ],
                        'ajax' => [
                            'url' => Url::toRoute(['user/search']),
                            'dataType' => 'json',
                            'data' => new JsExpression('function(params) { return {q:params.term }; }')
                        ],
                        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                        'templateResult' => new JsExpression('function(result) { return result.text; }'),
                        'templateSelection' => new JsExpression('function (result) { return result.text; }')
                    ]
                ])
            ],
            [
                'attribute' => 'approve_by',
                'label' => Yii::t('backend','Duyệt bởi'),
                'format' => 'raw',
                'headerOptions' => ['style' => 'width:15%'],

                'value' => function ($model) {
                    return ($model->auth_user)?$model->auth_user->username:'';
                },
                'filter' => Html::activeDropDownList($searchModel, 'approve_by', ArrayHelper::map(\common\models\AuthUser::getAllUser(), 'id', 'username'),['class'=>'form-control','prompt' => '']),
            ],
            [
                'attribute' => Yii::t('backend','Thao tác'),
                'format' => 'raw',
                'value' => function ($model) {
                    if ($model->checkApprovePermission()) {
                        $approveBtn = '<button style="width: 115px;" onclick="approveComment(' . $model->id . ', \'approve\')" type="button" class="btn btn-success video-btn-publish">'. Yii::t("backend", "Duyệt") .'</button>';
                        $deleteBtn = '<button style="width: 115px;" onclick="declineComment(' . $model->id . ', \'delete\')" id="declineCommentBtn" type="button" class="btn btn-danger video-btn-publish">'. Yii::t("backend", "Không duyệt") .'</button>';

                        switch ($model->status) {
                            case 0:
                                return $approveBtn . $deleteBtn;
                            case 1:
                                return $deleteBtn;
                            case 2:
                                return $approveBtn;
                        }
                    }
                },
            ],
        ],
    ]); ?>

</div>
<div id="myModal" class="modal fade in">
    <!-- Modal content -->
    <div class="modal-content">
        <div>
            <span class="close">&times;</span>
            <p><?= Yii::t('backend','Lý do không duyệt bình luận:')?></p>
        </div>
        <div>
            <?php
            $allReason = Yii::$app->params['setting.comment.decline'];
            ?>
            <ul class="list-group">
                <?php
                    foreach($allReason as $key=>$value):
                ?>
                    <label for="<?=$key?>" style="width: 500px; font-size: 13px; margin-bottom: -1px;">
                        <li class="list-group-item">
                            <input type="radio" id="<?=$key?>" name="reasonNum" value="<?=$key?>">
                            <?= Yii::t('wap', $value)?>
                        </li>
                    </label>
                <?php endforeach;?>
            </ul>
        </div>
        <input type="hidden" id="hiddenId"/>
        <input type="hidden" id="hiddenAction"/>
        <input type="button" id="reasonDecline" onclick="submitReasonDecline()" value="<?= Yii::t('backend','Lưu lại')?>" class="btn btn-primary" style="margin: 0 200px;"/>
    </div>
    <!-- Trigger/Open The Modal -->
    <button id="myBtn">Open Modal</button>

    <!-- The Modal -->
</div>


<div id="reason" class="modal fade in" role="dialog" tabindex="-1" aria-hidden="true" >
    <div class="modal-dialog" role="document" style="width: 400px" >
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?= Yii::t('backend','Thông báo')?></h4>
            </div>
            <div class="modal-body">
                <p class="modal-text"><?= Yii::t('backend','Bạn phải chọn 1 lý do từ chối duyệt!')?></p>
            </div>
            <div class="modal-footer footer-button" style="border-top: 1px solid #e5e5e5!important;">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?= Yii::t('backend','Cancel') ?></button>
            </div>
        </div>
    </div>
</div>

backend/views/vt-comment/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\VtComment */

$this->title = Yii::t('backend','Cập nhật bình luận').': ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend','Quản lý bình luận'), 'url' => !empty($homeUrl)? base64_decode($homeUrl):['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['update', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend','Cập nhật');
?>
<div class="vt-comment-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/vt-comment/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\VtComment */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Vt Comments'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vt-comment-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('backend', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'content_id',
            'type',
            'user_id',
            'content',
            'parent_id',
            'status',
            'bad_word_filter',
            'approve_by',
            'reason',
            'like_count',
            'created_at',
            'updated_at',
            'comment:ntext',
            'comment_count',
        ],
    ]) ?>

</div>