backend/models/VtChannelInfo.php
<?php

namespace backend\models;

use common\models\VtChannelInfoBase;
use Yii;

class VtChannelInfo extends \common\models\VtChannelInfoBase {
    public function rules()
    {
        return [
            [['status'], 'string'],
        ];
    }

    public function checkApprovePermission()
    {
        if (Yii::$app->user->can('vt-channel-info')) {
            return true;
        } else {
            return false;
        }
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'channel_id' => Yii::t('backend', 'Channel ID'),
            'status' => Yii::t('backend', 'Trạng thái'),
            'full_name' => Yii::t('backend', 'Tên kênh'),
            'bucket' => Yii::t('backend', 'Bucket'),
            'path' => Yii::t('backend', 'Path'),
            'channel_bucket' => Yii::t('backend', 'Channel Bucket'),
            'channel_path' => Yii::t('backend', 'Channel Path'),
            'description' => Yii::t('backend', 'Mô tả'),
            'reason' => Yii::t('backend', 'Lý do'),
            'created_at' => Yii::t('backend', 'Tạo lúc'),
            'updated_at' => Yii::t('backend', 'Cập nhật lúc'),
        ];
    }

    public static function getChannel($id){
        $channel = self::find()->where(['id' => $id])->one();
        return $channel;
    }
}

backend/controllers/VtChannelInfoController.php
<?php

namespace backend\controllers;

use common\helpers\Utils;
use Yii;
use backend\models\VtChannelInfo;
use backend\models\VtChannel;
use backend\models\VtChannelInfoSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use common\helpers\CustomDataProvider;
use yii\filters\VerbFilter;
use backend\models\VtActionLog;
use common\models\VtChannelInfoBase;
use yii\web\UploadedFile;
use common\libs\S3Service;
use common\libs\VtHelper;

/**
 * VtChannelInfoController implements the CRUD actions for VtChannelInfo model.
 */
class VtChannelInfoController extends Controller
{
    public  function init()
    {
        //parent::init(); // TODO: Change the autogenerated stub
        //$this->language = Yii::$app->session->get('lang', 'lo');
        $langss = Yii::$app->session->get('lang', 'lo');
        //var_dump($langss);die;
        // kiem tra xem this->language co nam trong mang khong
        $languagePool=Yii::$app->params['languagepool'];
        //var_dump($languagePool);die;
        // neu trong mang
        if(in_array($langss,$languagePool)){
            Yii::$app->language=$langss;
        }else{
            Yii::$app->language=Yii::$app->params['mainLanguage'];
        }
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all VtChannelInfo models.
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new VtChannelInfoSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single VtChannelInfo model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Updates an existing VtChannelInfo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            VtActionLog::insertLog(VtActionLog::MODULE_CHANNEL, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);

            return $this->redirect(['view', 'id' => $model->id]);

        } else {

            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing VtChannelInfo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the VtChannelInfo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return VtChannelInfo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = VtChannelInfo::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
        }
    }

    public function actionProcess(){

        if (!Yii::$app->getRequest()->validateCsrfToken()) {
            return Yii::t('backend', "CSRF TOKEN INVALID");
        }

        $id = Yii::$app->request->post('id',0);
        $reason = Yii::$app->request->post('reason',0);
        $action = Yii::$app->request->post('action',0);
        $model = $this->findModel($id);

        if ($model) {
            switch ($action) {
                case 'approve':
                    $model->status = 1;
                    $model->reason = null;
                    $model->save(false);
                    VtActionLog::insertLog(VtActionLog::MODULE_CHANNEL_CHANGE_INFO, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);
                    $channelModel = VtChannel::getChannel($model->channel_id);
                    $channelModel->full_name = $model->full_name;
                    $channelModel->path = $model->path;
                    $channelModel->channel_path =  $model->channel_path;
                    $channelModel->description = $model->description;
                    $channelModel->bucket = $model->bucket;
                    $channelModel->channel_bucket = $model->channel_bucket;
                    $channelModel->status = 1;
                    $channelModel->save(false);
                    VtActionLog::insertLog(VtActionLog::MODULE_CHANNEL, $channelModel, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);
                    echo json_encode(['errorCode' => 200, "message" => Yii::t('backend','Duyệt thành công')]);
                    break;

                case 'delete':
                    $model->status = 2;
                    $model->reason = $reason;
                    $model->save(false);
                    VtActionLog::insertLog(VtActionLog::MODULE_CHANNEL_CHANGE_INFO, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);
                    echo json_encode(['errorCode' => 200, "message" => Yii::t('backend','Hạ duyệt thành công')]);
                    break;
            }
        } else {
            return json_encode(['errorCode' => 201, "message" => Yii::t('backend','Không tìm thấy thông tin kênh')]);
        }
    }

    /**
     * Lists all VtChannelInfo models.
     * @return mixed
     */
    public function actionChannelAction()
    {

        $searchModel = new \backend\models\VtChannelSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index_add', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new VtChannelInfo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreateChannel()
    {
        $model = new VtChannel();
        $model = new VtChannel();
        $objChannel = new VtChannelInfoBase();
        $full_name = trim(Yii::$app->request->post()['VtChannel']['full_name']);
        $description = trim(Yii::$app->request->post()['VtChannel']['description']);
        $user_id = trim(Yii::$app->request->post()['VtChannel']['user_id']);
        $userLimit10 = count($model::getChannelAllById($user_id));

        if ($userLimit10 > 9) {
            Yii::$app->session->setFlash('error', Yii::t('wap','Bạn đã vượt qua số lượng 10 kênh trên hệ thống'));

            return $this->render('create', ['model' => $model]);
        }

        if ($model->load(Yii::$app->request->post())) {
            $model->status = VtChannelInfoBase::APPROVED;
            $model->is_hot = 0;
            $model->view_count = 0;
            $model->follow_count = 0;
            $model->video_count = 0;
            $model->created_at = date("Y-m-d H:i:s");
            $model->updated_at = date("Y-m-d H:i:s");
            $objChannel->created_at = date("Y-m-d H:i:s");
            $objChannel->updated_at = date("Y-m-d H:i:s");

            if (!empty($full_name)) {
                $objChannel->full_name = $full_name;
                $model->full_name;
            }

            if (!empty($description)) {
                $objChannel->description = $description;
                $model->description = $description;
            }

            if (!empty($user_id)) {
                $model->user_id = $user_id;
            }

            $model->saveWithImage($objChannel, $model);

            $objChannel->status =  VtChannelInfoBase::APPROVED;

            if ($model->save(false)) {
                $objChannel->channel_id = $model->id;
                $objChannel->save(false);

                VtActionLog::insertLog(VtActionLog::MODULE_CATEGORY, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);

                Yii::$app->session->setFlash('success', Yii::t('backend','Thêm mới thành công!'));
            }

            return $this->redirect(['update-channel', 'id' => $model->id]);

        } else {

            return $this->render('create', ['model' => $model]);
        }
    }

    public function actionUpdateChannel($id)
    {
        $model = VtChannel::findOne($id);
        $objChannel = VtChannelInfoBase::getChannelById($id);
        $oldPath = $model->path;
        $oldChannelPath = $model->channel_path;
        $full_name = trim(Yii::$app->request->post()['VtChannel']['full_name']);
        $description = trim(Yii::$app->request->post()['VtChannel']['description']);
        $user_id = trim(Yii::$app->request->post()['VtChannel']['user_id']);

        if ($model->load(Yii::$app->request->post())) {
            $model->path = $oldPath;
            $model->channel_path = $oldChannelPath;

            if(empty($objChannel)) {
                $objChannel = new VtChannelInfoBase();
                $objChannel->created_at = date("Y-m-d H:i:s");
                $objChannel->channel_id = $id;
                $model->updated_at = date("Y-m-d H:i:s");
            } else {
                $objChannel->updated_at = date("Y-m-d H:i:s");
                $model->updated_at = date("Y-m-d H:i:s");
            }

backend/views/vt-channel-info/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\libs\S3Service;

/* @var $this yii\web\View */
/* @var $model backend\models\VtChannelInfo */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vt-channel-info-form">
<input type="hidden" id="user-change-info-action" value="/vt-channel-info/process">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'channel_id')->textInput(['maxlength' => 11, 'readonly'=> true]) ?>

    <?= $form->field($model, 'status')->textInput(['readonly'=> true, 'value' => $model->getStatusString()]) ?>

    <?= $form->field($model, 'full_name')->textInput(['maxlength' => 255, 'readonly'=> true]) ?>

    <div style="padding-left: 15px;">
        <div class="row">
            <span style="font-size: 14px;"><?= Yii::t('backend','Ảnh avatar:')?> </span>
            <?php if (!$model->isNewRecord && !empty($model->path)): ?>
                <img class="preview-image" src="<?= S3Service::generateWebUrl($model->bucket, $model->path) ?>"/>
            <?php else: ?>
                <p><?= Yii::t('backend','(Không có ảnh)')?></p>
            <?php endif ?>
        </div>
        <br>
        <div class="row">
            <span style="font-size: 14px;"><?= Yii::t('backend','Ảnh banner:')?> </span>
            <?php if (!$model->isNewRecord && !empty($model->channel_path)): ?>
                <img class="image-preview-display" style="max-width: 1000px" src="<?= S3Service::generateWebUrl($model->channel_bucket, $model->channel_path) ?>"/>
            <?php else: ?>
                <p><?= Yii::t('backend','(Không có ảnh)')?></p>
            <?php endif ?>
        </div>
    </div>
    <br>
    <div>
        <p><?= Yii::t('backend','Mô tả của Channel')?></p>
        <textarea rows="6" readonly style="width: 100%; resize: none;"><?= $model->description?></textarea>
    </div>

    <div>
        <p><?= Yii::t('backend','Lý do từ chối')?></p>
        <textarea rows="6" readonly style="width: 100%; resize: none;"><?= $model->reason?></textarea>
    </div>

    <?= $form->field($model, 'created_at')->textInput(['readonly'=> true]) ?>

    <?= $form->field($model, 'updated_at')->textInput(['readonly'=> true]) ?>

    <div id="processButton">
        <?php
//        if ($model->checkApprovePermission()) {
            $approveBtn = '<button style="width: 115px;" onclick="approveUserChangeInfo(' . $model->id . ', \'approve\')" type="button" class="btn btn-success video-btn-publish">' . Yii::t("backend", "Duyệt") . '</button>';
            $deleteBtn = '<button style="width: 115px;" onclick="declineUserChangeInfo(' . $model->id . ', \'delete\')" type="button" class="btn btn-danger video-btn-publish">' . Yii::t("backend", "Không duyệt") . '</button>';

            switch ($model->status) {
                case 0:
                    echo $approveBtn . $deleteBtn;
                    break;
                case 1:
                    echo $deleteBtn;
                    break;
                case 2:
                    echo $approveBtn;
                    break;
            }
      //  }
        ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>
<input type="hidden" id="approve-user-change-info" value="/vt-channel-info/process">
<div id="userChangeInfoModal" class="modal">
    <div class="modal-content">
        <div>
            <span class="close">&times;</span>
            <p><?= Yii::t('backend','Lý do từ chối duyệt:')?></p>
        </div>
        <div>
            <textarea rows="4" id="declineUserChangeInfoReason" style="width: 100%; resize: none;"></textarea>
        </div>
        <input type="hidden" id="hiddenId"/>
        <input type="hidden" id="hiddenAction"/>
        <input type="button" id="reasonDecline" onclick="submitReasonDeclineUserChangeInfo()" value="<?php echo Yii::t('backend', 'Lưu lại')?>" class="btn btn-primary" style="margin: 0 200px;"/>
    </div>
</div>

backend/views/vt-channel-info/_form_insert.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\libs\S3Service;
use kartik\select2\Select2;
use yii\web\JsExpression;
use common\models\db\VtUserDB;
use \yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model backend\models\VtChannelInfo */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vt-channel-info-form">
    <!-- <input type="hidden" id="user-change-info-action" value="/vt-channel-info/process"> -->
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'full_name')->textInput(['maxlength' => 255])->label(Yii::t('backend', 'Tên channel') . '<span class="text-danger">*</span>') ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6, 'maxlength' => 10000])->label(Yii::t('backend', 'Mô tả') . '<span class="text-danger">*</span>') ?>

    <?php $user = VtUserDB::findOne($model->user_id); ?>
    <?= $form->field($model, 'user_id')->widget(Select2::classname(), [
        'initValueText' => $user ? $user->full_name : '',
        'options' => [
            'id' => 'user_id',
            'placeholder' => Yii::t('backend', 'Tên user') . ' ...'
        ],
        'pluginOptions' => [
            'allowClear' => true,
            'minimumInputLength' => 3,
            'language' => [
                'errorLoading' => new JsExpression("function () { return '" . Yii::t('backend', 'Loading') . "...'; }"),
            ],
            'ajax' => [
                'url' => Url::toRoute(['/user/search']),
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { return {q:params.term }; }')
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function(result) { return result.text; }'),
            'templateSelection' => new JsExpression('function (result) { return result.text; }'),
        ],
    ])->label(Yii::t('backend', 'Tên user'). '<span class="text-danger">*</span>'); ?>

    <?php if (!$model->isNewRecord && !empty($model->path)): ?>
        <div>
            <img class="preview-image" src="<?= S3Service::generateWebUrl($model->bucket, $model->path) ?>"/>
        </div>
    <?php endif ?>

    <?= $form->field($model, 'channel_path')->fileInput()->label(Yii::t('app', 'Ảnh đại diện')) ?>
    <label class="control-label color_red"><?= Yii::t('backend', 'Vui lòng chọn ảnh {extension}', ['extension' => 'JPG, PNG', 'size' => '180*180px'])?></label>

    <?php if (!$model->isNewRecord && !empty($model->path)): ?>
        <div>
            <img class="preview-image" src="<?= S3Service::generateWebUrl($model->channel_bucket, $model->channel_path) ?>"/>
        </div>
    <?php endif ?>

    <?= $form->field($model, 'path')->fileInput()->label(Yii::t('app', 'Ảnh banner')) ?>
    <label class="control-label color_red"><?= Yii::t('backend', 'Vui lòng chọn ảnh {extension}', ['extension' => 'JPG, PNG', 'size' => '1920*330px'])?></label>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end();?>
</div>
<input type="hidden" id="approve-user-change-info" value="/vt-channel-info/process">

backend/views/vt-channel-info/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\VtUserChangeInfoSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vt-user-change-info-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'full_name') ?>

    <?= $form->field($model, 'bucket') ?>

    <?php // echo $form->field($model, 'path') ?>

    <?php // echo $form->field($model, 'channel_bucket') ?>

    <?php // echo $form->field($model, 'channel_path') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'reason') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('backend', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vt-channel-info/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\libs\VtHelper;
use backend\assets\UserAsset;
UserAsset::register($this);

/* @var $this yii\web\View */
/* @var $searchModel backend\models\VtChannelInfoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend','Tool duyệt thông tin kênh');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vt-channel-info-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <a style="width: 115px;" href="/vt-channel-info/create-channel" class="btn btn-success"><?= Yii::t("backend", 'Tạo mới') ?></a>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'label' => Yii::t('backend','ID kênh'),
                'attribute' => 'channel_id',
                'contentOptions' => ['style'=>'text-align:right; width: 90px;'],
            ],
            [
                'attribute' => 'full_name',
                'contentOptions' => ['style'=>'max-width: 100px; word-break: break-all;'],
            ],
            [
                'attribute' => 'description',
                'contentOptions' => ['style'=>'max-width: 100px; word-break: break-all;'],
            ],
            [
                'label' => Yii::t('backend','Ảnh avatar'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::img(VtHelper::getThumbUrl($model->bucket , $model->path, VtHelper::SIZE_AVATAR), ['class' => 'image-grid-display']);
                }
            ],
            [
                'label' => Yii::t('backend','Ảnh banner'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::img(VtHelper::getThumbUrl($model->channel_bucket , $model->channel_path, VtHelper::SIZE_BANNER), ['class' => 'image-grid-display']);
                }
            ],
            [
                'attribute' => 'status',
                'value' => function($model, $key, $index, $widget) {
                    return $model->getStatusString();
                },
                'filter' => \common\helpers\Utils::getInterlizationParams('comment.status.dropdown.value', true, 'backend')
            ],
            [
                'attribute' => Yii::t('backend', 'Thao tác'),
                'format' => 'raw',
                'contentOptions' => ['style'=>'text-align:right; width: 115px;'],
                'value' => function ($model) {
//                    if ($model->checkApprovePermission()) {
                        $approveBtn = '<button style="width: 115px;" onclick="approveUserChangeInfoQuick(' . $model->id . ', \'approve\')" type="button" class="btn btn-success video-btn-publish">' . Yii::t("backend", "Duyệt") . '</button>';
                        $deleteBtn = '<button style="width: 115px;" onclick="declineUserChangeInfo(' . $model->id . ', \'delete\')" type="button" class="btn btn-danger video-btn-publish">' . Yii::t("backend", "Không duyệt"). '</button>';
                       // $waitapproveBtn = '<button style="width: 115px;" onclick="wai">'
                        $detailBtn = '<a style="width: 115px; background-color: yellowgreen;" href="/vt-channel-info/update?id='. $model->id .'" target="_blank" class="btn btn-success video-btn-publish">' . Yii::t("backend", "Chi tiết") . '</a>';

                        switch ($model->status) {
                            case 0:
                                return $approveBtn . $deleteBtn . '<br>'. $detailBtn;
                            case 1:
                               // return $deleteBtn . '<br>'. $detailBtn;
                                return $detailBtn;
                            case 2:
                                return $approveBtn . '<br>'. $detailBtn;

                        }
                        return $result;
//                    }
                },
            ],
        ],
    ]); ?>
</div>
<input type="hidden" id="approve-user-change-info" value="/vt-channel-info/process">
<div id="userChangeInfoModal" class="modal">
    <div class="modal-content">
        <div>
            <span class="close">&times;</span>
            <p><?= Yii::t('backend','Lý do từ chối duyệt')?>:</p>
        </div>
        <div>
            <textarea rows="4" id="declineUserChangeInfoReason" style="width: 100%; resize: none;"></textarea>
        </div>
        <input type="hidden" id="hiddenId"/>
        <input type="hidden" id="hiddenAction"/>
        <input type="button" id="reasonDecline" onclick="submitReasonDeclineUserChangeInfoQuick()" value="<?= Yii::t('backend', 'Lưu lại')?>" class="btn btn-primary" style="margin: 0 200px;"/>
    </div>
</div>

backend/views/vt-channel-info/index_add.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\libs\VtHelper;
use backend\assets\UserAsset;
UserAsset::register($this);

/* @var $this yii\web\View */
/* @var $searchModel backend\models\VtChannelInfoSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend','Tool duyệt nhanh thông tin kênh');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vt-channel-info-index">
    <a style="width: 115px;" href="/vt-channel-info/create-channel" class="btn btn-success"><?= Yii::t("backend", 'Tạo mới') ?></a>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'label' => Yii::t('backend','ID kênh'),
                'attribute' => 'id',
                'contentOptions' => ['style'=>'width: 120px;'],
            ],
            [
                'label' => Yii::t('backend','Tên channel'),
                'attribute' => 'full_name',
                'contentOptions' => ['style'=>'max-width: 100px; word-break: break-all;'],
            ],
            [
                'label' => Yii::t('backend','Mô tả'),
                'attribute' => 'description',
                'contentOptions' => ['style'=>'max-width: 100px; word-break: break-all;'],
            ],
            [
                'label' => Yii::t('backend','Ảnh avatar'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::img(VtHelper::getThumbUrl($model->channel_bucket , $model->channel_path, VtHelper::SIZE_BANNER), ['class' => 'image-grid-display']);
                }
            ],
            [
                'label' => Yii::t('backend','Ảnh banner'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::img(VtHelper::getThumbUrl($model->bucket, $model->path, VtHelper::SIZE_AVATAR), ['class' => 'image-grid-display']);
                }
            ],
            // [
            //     'attribute' => 'status',
            //     'format' => 'raw',
            //     'value' => function($model, $key, $index, $widget) {
            //         return $model->getStatusString();
            //     },

            //     'filter' => \common\helpers\Utils::getInterlizationParams('comment.status.dropdown.value', true, 'backend')
            // ],
            [
                'attribute' => Yii::t('backend', 'Thao tác'),
                'format' => 'raw',
                'contentOptions' => ['style'=>'text-align:right; width: 115px;'],
                'value' => function ($model) {
                    $detailBtn = '<a style="width: 115px; background-color: yellowgreen;" href="/vt-channel-info/update-channel?id='. (int)($model->id) .'" target="_blank" class="btn btn-success video-btn-publish">' . Yii::t("backend", "Chi tiết") . '</a>';
                    return $detailBtn;
                },
            ],
        ],
    ]);?>
</div>
<input type="hidden" id="approve-user-change-info" value="/vt-channel-info/process">
<div id="userChangeInfoModal" class="modal">
    <div class="modal-content">
        <div>
            <span class="close">&times;</span>
            <p><?= Yii::t('backend','Lý do từ chối duyệt')?>:</p>
        </div>
        <div>
            <textarea rows="4" id="declineUserChangeInfoReason" style="width: 100%; resize: none;"></textarea>
        </div>
        <input type="hidden" id="hiddenId"/>
        <input type="hidden" id="hiddenAction"/>
        <input type="button" id="reasonDecline" onclick="submitReasonDeclineUserChangeInfoQuick()" value="<?= Yii::t('backend', 'Lưu lại')?>" class="btn btn-primary" style="margin: 0 200px;"/>
    </div>
</div>