cp/controllers/UserController.php
<?php

namespace cp\controllers;

use common\models\VtUserBase;
use wap\models\VtUser;
use Yii;
use common\models\AuthUser;
use backend\models\UserSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }


    /**
     * Change password an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionChange()
    {
        $model = $this->findModel(Yii::$app->user->id);
        $pass = $model->password_hash;
        if ($model->load(Yii::$app->request->post())) {
            $oldPass = trim(Yii::$app->request->post()[$model->formName()]['password_old']);
            if (password_verify($oldPass, $pass)) {
                $passWeak = \Yii::$app->params['pass-weak'];
                $newPass = trim(Yii::$app->request->post()[$model->formName()]['password_hash']);
                if ($oldPass != $newPass) {
                    if (!in_array($newPass, $passWeak)) {
                        $model->is_first_login = 0;
                        if ($model->save()) {
                            \Yii::$app->user->login($model, 1800);
                            return $this->goHome();
                        }
                    } else {
                        $model->addError('password_hash', 'Mật khẩu mới chưa đủ mạnh!');
                    }
                } else {
                    $model->addError('password_hash', 'Mật khẩu mới không được trùng với mật khẩu cũ!');
                }
            } else {
                $model->addError('password_old', 'Mật khẩu cũ không đúng!');
            }
        }
        return $this->render('change', [
            'model' => $model,
        ]);
    }


    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = AuthUser::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSearch()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $q = Yii::$app->request->get('q');
        $out = ['results' => ['id' => '', 'text' => '']];

        $arr = VtUserBase::find()
            ->asArray()
            ->where("full_name like :name or msisdn like :name", ['name' => "%" . $q . "%"])
            ->all();

        $cc = 0;
        $result = [];
        foreach ($arr as $item) {
            $result[$cc]['id'] = $item['id'];
            $result[$cc]['text'] = $item['id'] . '-' . $item['full_name'];
            $cc++;
        }
        $out['results'] = $result;

        return $out;
    }

}

cp/views/user/_change.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\VtUser */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vt-user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'password_old')->passwordInput() ?>

    <?= $form->field($model, 'password_hash')->passwordInput(['value' => ''])->label('Mật khẩu mới') ?>

    <?= $form->field($model, 're_password')->passwordInput()->label('Gõ lại mật khẩu mới') ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'status')->checkbox() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

cp/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\web\JsExpression;
use yii\helpers\ArrayHelper;
use cp\models\VtCp;

/* @var $this yii\web\View */
/* @var $model backend\models\VtUser */
/* @var $form yii\widgets\ActiveForm */
?>
<?php
    $url = \yii\helpers\Url::toRoute(['user/search']);
?>

<div class="vt-user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'password_hash')->passwordInput() ?>

    <?= $form->field($model, 're_password')->passwordInput() ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'status')->checkbox() ?>


    <?= $form->field($model, 'user_id')->widget(Select2::classname(), [
        'initValueText' => $model->getWapUserName(),
        'options' => ['placeholder' => 'Tìm kiếm User ...'],
        'pluginOptions' => [
            'allowClear' => true,
            'minimumInputLength' => 3,
            'language' => [
                'errorLoading' => new JsExpression("function () { return 'Loading ...'; }"),
            ],
            'ajax' => [
                'url' => $url,
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { return {q:params.term }; }')
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function(result) { return result.text; }'),
            'templateSelection' => new JsExpression('function (result) { return result.text; }')
        ]

    ])->label(Yii::t('app', 'Chọn User WAP'));
    ?>

    <?= $form->field($model, 'cp_id')->dropDownList(ArrayHelper::map(VtCp::getAllCp(), 'id', 'name'), ['class' => 'form-control package-checkbox-list', 'prompt'=>'--- Chọn đối tác ---']); ?>



    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

cp/views/user/change.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\VtUser */

$this->title = Yii::t('backend', 'Update {modelClass}: ', [
            'modelClass' => Yii::t('backend', 'Vt Users'),
        ]) . ' ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Vt Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="vt-user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_change', [
        'model' => $model,
    ])
    ?>

</div>