backend/models/VtUser.php
<?php

namespace backend\models;

use Yii;
use common\helpers\Utils;
use common\libs\S3Service;
use common\libs\VtHelper;
use yii\web\UploadedFile;

class VtUser extends \common\models\VtUserBase {
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_hot', 'cp_id'], 'integer'],
            [['status'], 'string'],
            [['msisdn','priority'], 'integer', 'min' => 0, 'tooSmall' => Yii::t('backend','{attribute} không được nhỏ hơn 0'), 'message' =>Yii::t('backend','{attribute} phải là số nguyên')],
            [['last_login', 'is_show_suggest', 'changed_password', 'follow_count', 'video_count'], 'safe'],
            [['password', 'full_name','oauth_id'], 'string', 'max' => 50],
            [['email'],'email'],
            [['salt', 'bucket'], 'string', 'max' => 255],
            [['msisdn', 'status', 'full_name'], 'required', 'message' => Yii::t('backend','{attribute} không được để trống') ],
            [['otp'], 'string', 'max' => 10],
            [['path'], 'safe'],
            [['path'], 'file', 'extensions' => 'jpg,jpeg,png', 'mimeTypes' => 'image/jpeg,image/pjpeg,image/png,image/x-png', 'wrongExtension' => Yii::t('backend','Chỉ cho phép các tệp có các phần mở rộng này: jpg, jpeg, png.')],
            [['channel_path'], 'safe'],
            [['channel_path'], 'file', 'extensions' => 'jpg,jpeg,png', 'mimeTypes' => 'image/jpeg,image/pjpeg,image/png,image/x-png', 'wrongExtension' => Yii::t('backend','Chỉ cho phép các tệp có các phần mở rộng này: jpg, jpeg, png.')],
        ];
    }

    public function saveWithImage($avatarDelete = '', $bannerDelete = '')
    {
        $file = UploadedFile::getInstance($this, 'path');
        $channelFile = UploadedFile::getInstance($this, 'channel_path');

        if (!empty($file)) {
            /*$bucket = Yii::$app->params['s3']['static.bucket'];

            $path = Utils::generatePath($file->extension);

            S3Service::putObject($bucket, $file->tempName, $path);

            VtHelper::generateAllThumb($bucket, $file->tempName, $path);

            $this->bucket = $bucket;
            $this->path = $path;*/

            $dirName = $this->path ? dirname($this->path) : dirname('media2/images/attribute/' . Utils::generatePath($file->extension));

            $uploadResult = VtHelper::uploadAndGenerateThumbs($file, $dirName);
            $this->path = $uploadResult['path'];

            if(isset($uploadResult['bucket'])) {
                $this->bucket = $uploadResult['bucket'];
            }
        } else {
            if($avatarDelete == "1"){
                $this->path = null;
            } else{
                unset($this->path);
            }
            unset($this->bucket);
        }

        if (!empty($channelFile)) {
            /*$channelBucket = Yii::$app->params['s3']['static.bucket'];

            $channelPath = Utils::generatePath($channelFile->extension);

            S3Service::putObject($channelBucket, $channelFile->tempName, $channelPath);

            VtHelper::generateAllThumb($channelBucket, $channelFile->tempName, $channelPath);

            $this->channel_bucket = $channelBucket;
            $this->channel_path = $channelPath;*/
            $dirName = $this->channel_path ? dirname($this->channel_path) : dirname('media2/images/attribute/' . Utils::generatePath($file->extension));
            $uploadResult = VtHelper::uploadAndGenerateThumbs($channelFile, $dirName);
            $this->channel_path = $uploadResult['path'];

            if(isset($uploadResult['bucket'])) {
                $this->channel_bucket = $uploadResult['bucket'];
            }
        } else {
            if($bannerDelete == "1"){
                $this->channel_path = null;
            } else{
                unset($this->channel_path);
            }
            unset($this->channel_bucket);
        }
        $this->save();
    }


    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend','ID'),
            'msisdn' => Yii::t('backend','Số điện thoại'),
            'status' => Yii::t('backend','Trạng thái'),
            'password' => Yii::t('backend','Password'),
            'salt' => Yii::t('backend','Salt'),
            'full_name' => Yii::t('backend','Tên hiển thị'),
            'email' => Yii::t('backend','Email'),
            'oauth_id' => Yii::t('backend','Oauth ID'),
            'follow_count' => Yii::t('backend','Follow Count'),
            'otp' => Yii::t('backend','Otp'),
            'last_login' => Yii::t('backend','Last Login'),
            'changed_password' => Yii::t('backend','Changed Password'),
            'bucket' => Yii::t('backend','Bucket'),
            'path' => Yii::t('backend','Path'),
            'video_count' => Yii::t('backend','Video Count'),
            'is_show_suggest' => Yii::t('backend','Is Show Suggest'),
            'priority' => Yii::t('backend','Thứ tự'),
        ];
    }

    public static function getUser($id){
        $user = self::find()->where(['id' => $id])->one();
        return $user;
    }
}

backend/models/VtUserView.php
<?php

namespace backend\models;

use Yii;

class VtUserView extends \common\models\VtUserViewBase {

}

backend/controllers/VtUserController.php
<?php

namespace backend\controllers;

use backend\models\VtActionLog;
use backend\models\VtUserHotSearch;
use richardfan\sortable\SortableAction;
use Yii;
use backend\models\VtUser;
use backend\models\VtUserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * VtUserController implements the CRUD actions for VtUser model.
 */
class VtUserController extends Controller
{
    public  function init()
    {
        //parent::init(); // TODO: Change the autogenerated stub
        //$this->language = Yii::$app->session->get('lang', 'lo');
        $langss = Yii::$app->session->get('lang', 'lo');
        //var_dump($langss);die;
        // kiem tra xem this->language co nam trong mang khong
        $languagePool=Yii::$app->params['languagepool'];
        //var_dump($languagePool);die;
        // neu trong mang
        if(in_array($langss,$languagePool)){
            Yii::$app->language=$langss;
        }else{
            Yii::$app->language=Yii::$app->params['mainLanguage'];
        }
    }

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actions(){
        return [
            'sortItem' => [
                'class' => SortableAction::className(),
                'activeRecordClassName' => VtUser::className(),
                'orderColumn' => 'priority',
            ],

        ];
    }

    /**
     * Lists all VtUser models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new VtUserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new VtUser model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new VtUser();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->saveWithImage();

            VtActionLog::insertLog(VtActionLog::MODULE_USER, $model, VtActionLog::TYPE_CREATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);
            Yii::$app->session->setFlash("success",Yii::t('backend','Thêm mới thành công'));


            return $this->redirect(['update', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }



    /**
     * Updates an existing VtUser model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $params = Yii::$app->request->post();
            $avatarDelete = $params['avatarDelete'];
            $bannerDelete = $params['bannerDelete'];
            $model->saveWithImage($avatarDelete, $bannerDelete);

            VtActionLog::insertLog(VtActionLog::MODULE_USER, $model, VtActionLog::TYPE_UPDATE, Yii::$app->user->identity->getId(), VtActionLog::SOURCE_BACKEND);
            Yii::$app->session->setFlash("success",Yii::t('backend','Chỉnh sửa thành công'));

            return $this->redirect(['update', 'id' => $model->id]);

        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Finds the VtUser model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return VtUser the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = VtUser::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
        }
    }

    public function actionIndexHot()
    {
        $searchModel = new VtUserHotSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $model = new VtUser();

        return $this->render('index_hot', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model

        ]);
    }

    public function actionCreateHot()
    {
        $param = Yii::$app->request->post();
        if(isset($param['VtUser']['id'])){
            if($param['VtUser']['id'] != null)
            {
                $model = $this->findModel($param['VtUser']['id']);
                $model->is_hot = VtUser::HOT;
                $model->priority = VtUser::getLastestPosition();

                if ($model->save(false)) {
                    \Yii::$app->session->setFlash('success', \Yii::t('app', 'Create successfully'));
                }else{
                    \Yii::$app->session->setFlash('error', \Yii::t('app', 'Create fail'));
                }
            }
            else  Yii::$app->session->setFlash("error",Yii::t('backend','Phải chọn kênh cần thêm'));
        }
        return $this->redirect(['index-hot']);

    }
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        Yii::$app->session->setFlash('success', Yii::t('backend','Xóa thành công!'));
        return $this->redirect(['index']);
    }


    public function actionSearch()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $q = Yii::$app->request->get('q');
        $out = ['results' => ['id' => '', 'text' => '']];
        $arr = VtUser::find()->where(['LIKE', 'full_name', '%' . $q . '%', false])->asArray()->select('id, full_name')->all();
        $cc = 0;
        $result = [];

        foreach ($arr as $item) {
            $result[$cc]['id'] = $item['id'];
            $result[$cc]['text'] = $item['full_name'];
            $cc++;
        }

        $out['results'] = $result;

        return $out;
    }



}

backend/views/vt-user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\libs\S3Service;
use cp\models\VtCp;

/* @var $this yii\web\View */
/* @var $model backend\models\VtUser */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vt-user-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'msisdn')->textInput()->label(Yii::t('backend','Số điện thoại'). '*') ?>


    <?= $form->field($model, 'status')->label(Yii::t('backend','Trạng thái'). '*')->dropDownList(
        \common\helpers\Utils::getInterlizationParams('user.status.dropdown.value', true, 'backend'),
        [
            'class' => 'form-control',
            'prompt' => '--- '.Yii::t('backend','Chọn trạng thái').' ---'
        ]

    )?>

    <?= $form->field($model, 'full_name')->textInput(['maxlength' => 50]) -> label(Yii::t('backend', 'Tên hiển thị'). '*') ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => 50]) ?>

    <div class="row">
        <div class="col-md-6">
            <input type="hidden" id="avatarDelete" name="avatarDelete">
            <?php if (!$model->isNewRecord && !empty($model->path)): ?>
                <div class="col-md-4 avatar-area" style="text-align: center">
                    <?php
                        $urlAvatar = S3Service::generateWebUrl($model->bucket, $model->path);
                    ?>
                    <img class="preview-image" src="<?= $urlAvatar; ?>"/>
                    <br>
                    <a href="<?= $urlAvatar; ?>" target="_blank" style="color: #0F9E5E; font-style: italic;"><?= Yii::t('backend','Xem cỡ lớn')?></a> | <a href="#" onclick="deleteAvatar()" style="color: #9A12B3; font-style: italic;"><?= Yii::t('backend','Xóa avatar')?></a>
                </div>
            <?php endif ?>
            <div class="col-md-8">
                <?= $form->field($model, 'path')->fileInput()->label(Yii::t('app', 'Ảnh đại diện')) ?>
            </div>
        </div>
        <div class="col-md-6">
            <input type="hidden" id="bannerDelete" name="bannerDelete">
            <?php if (!$model->isNewRecord && !empty($model->channel_path)): ?>
                <div class="col-md-4 banner-area" style="text-align: center">
                    <?php
                        $urlBanner = S3Service::generateWebUrl($model->channel_bucket, $model->channel_path);
                    ?>
                    <img class="preview-image" src="<?= $urlBanner; ?>"/>
                    <br>
                    <a href="<?= $urlBanner; ?>" target="_blank" style="color: #0F9E5E; font-style: italic;"><?= Yii::t('backend','Xem cỡ lớn')?></a> | <a href="#" onclick="deleteBanner()" style="color: #9A12B3; font-style: italic;"><?= Yii::t('backend','Xóa banner')?></a>
                </div>
            <?php endif ?>
            <div class="col-md-8">
                <?= $form->field($model, 'channel_path')->fileInput()->label(Yii::t('app', 'Ảnh cover')) ?>
            </div>
        </div>
    </div>


    <?= $form->field($model, 'priority')->textInput(['maxlength' => 50])->label(Yii::t('app', 'Thứ tự')) ?>

    <?= $form->field($model, 'is_hot')->checkbox(['label' => Yii::t('app', 'Hot')]) ?>

    <?= $form->field($model, 'cp_id')->dropDownList(ArrayHelper::map(VtCp::getAllCp(), 'id', 'name'), ['class' => 'form-control package-checkbox-list', 'prompt'=>'--- '.Yii::t('backend','Chọn đối tác').' ---'])->label(Yii::t('backend', 'Đối tác')); ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('backend', 'Create') : Yii::t('backend', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

    </div>

    <?php ActiveForm::end(); ?>


</div>

backend/views/vt-user/_form_hot.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\web\JsExpression;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model backend\models\VtUser */
/* @var $form yii\widgets\ActiveForm */



?>

<div class="row">

    <?php $form = ActiveForm::begin(['action' => Url::toRoute(['vt-user/create-hot'])]); ?>

    <div class="col-md-4">

        <?php $userName = empty($model->id) ? '' : \backend\models\VtUser::findOne($model->id)->getCreatedByName();?>

        <?= $form->field($model, 'id')->widget(Select2::classname(), [
            'initValueText' => $userName, // set the initial display text
            'options' => ['placeholder' => Yii::t('backend','Tìm kiếm kênh').' ...'],
            'pluginOptions' => [
                'allowClear' => true,
                'minimumInputLength' => 2,
                'language' => [
                    'errorLoading' => new JsExpression("function () { return '" . Yii::t('backend', 'Waiting for results...') . "'; }"),
                ],
                'ajax' => [
                    'url' => Url::toRoute(['user/search']),
                    'dataType' => 'json',
                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                ],
                'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                'templateResult' => new JsExpression('function(user) { return user.text; }'),
                'templateSelection' => new JsExpression('function (user) { return user.text; }'),
            ],
        ])->label(false);?>
    </div>


    <div class="col-md-4">
        <div class="form-group">
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Thêm mới') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vt-user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\VtUserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="vt-user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'msisdn') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'password') ?>

    <?= $form->field($model, 'salt') ?>

    <?php // echo $form->field($model, 'full_name') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'oauth_id') ?>

    <?php // echo $form->field($model, 'follow_count') ?>

    <?php // echo $form->field($model, 'otp') ?>

    <?php // echo $form->field($model, 'last_login') ?>

    <?php // echo $form->field($model, 'changed_password') ?>

    <?php // echo $form->field($model, 'bucket') ?>

    <?php // echo $form->field($model, 'path') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('backend', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/vt-user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\VtUser */

$this->title = Yii::t('backend','Thêm mới Khách hàng');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend','Khách hàng'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vt-user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/vt-user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\libs\VtHelper;


/* @var $this yii\web\View */
/* @var $searchModel backend\models\VtUserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend','Khách hàng');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vt-user-index">

    <!--h1><?= Html::encode($this->title) ?></h1-->
    <?php // echo $this->render('_search', ['model' => $searchModel]);
        $temp = Yii::$app->params['user.status.dropdown.value'];
        for($i = 0; $i < count($temp); $i++) {
            $temp[$i] = Yii::t('backend', $temp[$i]);
        }
    ?>
    <p>
        <?= Html::a(Yii::t('backend','Thêm mới Khách hàng'), ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('backend','Sắp xếp kênh Hot'), ['index-hot'], ['class' => 'btn btn-danger']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'summaryOptions' => ['class' => 'summary'],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'id',
                'filter' => false,
            ],
            'msisdn',
            [
                'attribute' => 'status',
                'label' => \Yii::t('app', 'Trạng thái'),
                'value' => function($model, $key, $index, $widget) {
                    return $model->getStatusString();
                },
                'filter' => $temp
            ],
            'full_name',
            'cp_id',
            'email:email',
            [
                'attribute' => 'Image',
                'label' => Yii::t('backend','Ảnh'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::img(VtHelper::getThumbUrl($model->bucket, $model->path, VtHelper::SIZE_AVATAR), ['class' => 'image-grid-display']);
                }
            ],
            ['class' => 'yii\grid\ActionColumn', 'template'=>'{update}{delete}'],
        ],
    ]); ?>

</div>

backend/views/vt-user/index_hot.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\libs\VtHelper;
use richardfan\sortable\SortableGridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\VtUserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend','Sắp xếp kênh Hot');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="vt-user-index">


    <?= $this->render('_form_hot', [
        'model' => $model,
    ]) ?>

    <?= SortableGridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'sortUrl' => Url::to(['sortItem']),

        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'msisdn',
            [
                'attribute' => 'status',
                'label' => \Yii::t('app', 'Trạng thái'),
                'value' => function($model, $key, $index, $widget) {
                    return $model->getStatusString();
                },
                'filter' => Yii::$app->params['user.status.dropdown.value']
            ],
            'full_name',
            'email:email',
            [
                'attribute' => 'Image',
                'label' => Yii::t('backend','Ảnh'),
                'format' => 'raw',
                'value' => function ($model) {
                    return Html::img(VtHelper::getThumbUrl($model->bucket, $model->path, VtHelper::SIZE_AVATAR), ['class' => 'image-grid-display']);
                }
            ],
            ['class' => 'yii\grid\ActionColumn','template'=>'{update}{delete}'],
        ],
    ]); ?>

</div>

backend/views/vt-user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\VtUser */

$this->title = Yii::t('backend','Chỉnh sửa Khách hàng').': ' . ' ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend','Khách hàng'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['update', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('backend','Cập nhật');
?>
<div class="vt-user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>